### ISSUE TITLE
Scale box manipulation wand

### ISSUE THREAD

**Issue by qouteall** [qouteall/MiniScaledMod#8]
From https://discord.com/channels/662271867431682058/971858753022464070/988008768480624650
Craft: s - stick, n - netherite ingot, a - amethyst crystal, 0 - empty
3x3 grid:
00a
0n0
s00

By default, rotates a scaled box around one of the axis when you right click on one of the faces. The scaled box would rotate around that face. Example: right-clicking at upper face would rotate scaled box around Y axis, right-clicking northern face would rotate the box around X axis.
If you would right click the wand while not pointing at any scaled box, the wand would change its mode.
If would have 3 modes: rotation (which I already explained), scale and gravity.
Scale and gravity modes would just toggle teleportChangesScale and teleportChangesGravity tags of the scaled box

**Comment by midblep** [comment]
What version added this item? I believe it's 1.19.3 from the release dates, and I don't seem to have it on the 1.19.0 version for this mod, since I'd like to play with 1.19.2 because of some other mods. 

I'd like to be able to turn off the automatic rescaling when Pehkui is installed, and be able to resize the scale box. Is it possible to backport to 1.19.2 or update the 1.19.0 version with this item? Or is there another way to achieve the effects the wand does?
